version: '3.7'
services:
  mongodb_container:
    image: mongo:5.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: email
    ports:
      - 27017:27017

volumes:
  mongodb_data_container: